version: '3'
services:
  xevo-api:
    build: ./xevo-api
    ports:
      - "3000:3000"
    depends_on:
      - xevo-cpp-server
  xevo-cpp-server:
    build: ./xevo-cpp-server
    ports:
      - "8080:8080"
  # xevo-game:
  #   build: ./xevo-game
  #   ports:
  #     - "4200:80"
